const body = document.querySelector('body');
const h3 = document.createElement('h3');
h3.innerText = 'Any type of string that we want';
body.appendChild(h3);
const ol = document.createElement('ol');
const li = document.createElement('li');
ol.innerHTML = '<li>this is the first item</li>';
li.innerHTML = 'this is a line item';
h3.appendChild(li);
h3.appendChild(ol);
